---
title: "lab_7 script"
author: "Deanna Strayer, Alex Newson, Sabreen NoorAli, Tony Daza, Seulbi Lee"
date: "11/2/2022"
output: html_document
bibliography: references.bib
csl: apa-annotated-bibliography.csl
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 6.5, fig.height = 8)
```

```{r}
library(tidyverse)
library(here)
library(rio)
library(janitor)
library(ggplot2)

star <- import(here("data","star.csv"), setclass="tbl_df") %>%
  clean_names()

```

```{r}
ggplot(star, aes(x = totexp, y = tmathss )) + 
  geom_point(aes(color = "grey", alpha = 0.5)) + 
  geom_smooth(method = lm, se = TRUE) +
  theme_minimal() + 
  labs(x = "Teacher Experience(years)", 
       y = "Total Math Scale Score",
       title = "Relation between Teacher Experience and Math Score",
       subtitle = "Separate Regression lines displayed by free/reduced price lunch status", 
       color = "lunch status")
```

This is r-markdown document has [@vanderheyden_is_2018] as a reference.

This is r-markdown document has [@polikoff_instructional_2010] as a reference.

This is r-markdown document has Naumann et al.'s article [-@naumann_sensitivity_2019] as a reference.

This is r-markdown document has Stockard et al.'s article [-@stockard_effectiveness_2018] as a reference.


# References
